### PR TITLE
Add support for custom textures

### PR DESCRIPTION
**Pull request by filnet**
Initial work to support custom textures.

Some issues/open questions:
- 16 descriptor sets are created upfront.  Is that ok ?
- Not sure updating descriptor sets as is done is "thread safe" ?
- The textures map stores (vk::ImageView, vk::Sampler) tuples. Is it acceptable ?

### CODE REVIEW

**Comment by filnet** [comment]
It is not valid to [update descriptor sets](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#vkUpdateDescriptorSets) if it is bound to a command buffer.

Solution #1:
Allow updating descriptor sets that are bound with the use of the `VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT` flag.
But this requires users to enable this feature when creating the device.

Pros: 
* simple

Cons:
* adds burden on the user when creating the device.

Solution #2:

Maintain "blueprints" descriptor sets and copy them when required as described [here](https://ourmachinery.com/post/vulkan-descriptor-sets-management/).

Pros: 
* transparent to user

Cons:
* more complex to implement

@adrien-ben any thoughts ?

**Comment by filnet** [comment]
Changes for solution one: https://github.com/adrien-ben/imgui-rs-vulkan-renderer/pull/3/commits/52c273580b360b388f9b1430af73f45bb2d5739f

**Comment by adrien-ben** [comment]
Sorry for the late response it's been a busy week. 

Maybe the easier version is to let the user manage it's descriptor sets and store these sets in the textures map. What do you think about it ?

**Comment by filnet** [comment]
> Maybe the easier version is to let the user manage it's descriptor sets and store these sets in the textures map. What do you think about it ?

That could work too. I'll think about it.
I also want to take a look at how it was handled for other back-ends and for other languages.

In the meantime I have working code for the "blueprint" approach. The code is very far from production quality and creates a lot of descriptor sets (but is it a problem?). I'll try to find the time to share it here.

**Comment by filnet** [comment]
Just pushed a new version of the branch with the "blue print" approach.

@adrien-ben could you release a new version with my last two contributions. will make my life easier.

Will now try out your suggested solution of storing the descriptor sets in the texture map.

**Comment by adrien-ben** [comment]
I just released a 0.3.2 version. I'll probably release a 0.4.0 version since imgui-rs just released a new version.

**Comment by filnet** [comment]
Today I'll push a new PR with the suggested approach of storing the descriptor set in the texture map.
This approach is much simpler and is perfect for simple use cases (where the image view and sampler are static and don't change from frame to frame).

**Comment by filnet** [comment]
Just pushed a initial version of texture support.

It stores user provided descriptor set in a texture map and binds the appropriate descriptor set when needed.

Some of the code is inspired by the imgui-glium-renderer and imgui-gfx-renderer projects:
- using TextureId(usize::MAX) as the fonts texture id
- introducing a BadTexture in the RendererError enum

PS : the README.md needs to be updated and some more doc is probably needed too.

**Comment by filnet** [comment]
Here it is in action:
image

First image is the depth buffer.
Second is the imgui fonts texture.

**Comment by adrien-ben** [comment]
For some reasons the 0.4.0 got publish even though I did not tag it. It seems Github actions just ignored the "on_tag" instruction...

So I will merge it on master. Sorry for the inconvenience.

Regarding your PR, it looks good to me. As you said readme and docs should be updated. And maybe an example. So far I "copied" the examples from the imgui-rs repo: https://github.com/Gekkio/imgui-rs/tree/master/imgui-examples/examples

**Comment by filnet** [comment]
I looked at writing a custom textures example based on the one in imgui-rs.
Looks doable but it requires a lot of vulkan boiler plate code (creating descriptors, transferring textures, ...).

Most of the needed code is in vulkan.rs already but it is not accessible from examples.
Any ideas ?

**Comment by filnet** [comment]
I pushed a quick and dirty adaptation of the imgui-rs custom-textures example.
It is really dirty... but works:

image

**Comment by filnet** [comment]
@adrien-ben please take a look when you have the time.

**Comment by adrien-ben** [comment]
Hi, I will look at it next weekend, code looks alright to me. I just need to run the example and use it on a project.

**Comment by adrien-ben** [comment]
It's all good to me, if you're good too, I'm ready to merge and release a 0.4.1.

**Comment by filnet** [comment]
I am good too.

**Comment by adrien-ben** [comment]
0.4.1 is now available. Thanks for your work !

**Pull request merged**
