### PR TITLE
Cya Lenna

### PR DESCRIPTION
**Pull request by filnet**

### CODE REVIEW

**Comment by filnet** [comment]
Please consider merging this PR.

**Comment by adrien-ben** [comment]
Hi, sorry I've been busy lately. I'm okay with the PR but just out of curiosity, why make this change ?

**Comment by filnet** [comment]
I came to know that the lady in the picture has expressed her desire to see the picture disappear.
So...

**Comment by filnet** [comment]
PS: I am the one who added the picture.

**Comment by adrien-ben** [comment]
Ok, thanks for the info. Bye Lenna then and welcome citrus !

**Pull request merged**
